#                                                        LINEAR ALGEBRA Assignment


In [39]:
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 15 02:17:49 2019

@author: Krishna Teja KANCHERLA

                                      **** LINEAR ALGEBRA ****
"""
import numpy as np
import numpy.linalg as la
import sympy as sym

In [25]:
#Excercise 1
#****************************************************************************
u=[1,2,1]
v=[1,4,4]
w=[-2,-1,2]

B = np.array([u,v,w]) 

print ("Determinant of Matrix is : ",la.det(B)) # aprrox -1 

#Ques-1 - Show that B = (u, v, w) is a basis of E

Z = np.array([0,0,0])
sol = la.solve(B,Z)
print("λ1, λ2, λ3 values are : ",sol)
print("3 Vectors(u, v, w) are Linearly Independent : ",B, " is Basis of E")
# Above solution says B is the basis  because the solution with all values=0 conveys 
# -> the columns are independent
# -> Span is R3
# Hence shown B = (u,v,w) is a basic of E 

Determinant of Matrix is :  -0.9999999999999993
λ1, λ2, λ3 values are :  [-0.  0. -0.]
3 Vectors(u, v, w) are Linearly Independent :  [[ 1  2  1]
 [ 1  4  4]
 [-2 -1  2]]  is Basis of E


In [26]:
#Ques-2
a = np.array([1,1,1])
y = np.linalg.solve(B,a)#    Solve a linear matrix equation, or system of linear scalar equations.
print("Coordinates of 'a' in this Basis are : ",y)

Coordinates of 'a' in this Basis are :  [-11.   9.  -6.]


In [27]:
#Question3
sym.init_printing()
λ_1,λ_2,λ_3 = sym.symbols('λ_1,λ_2,λ_3')#    Transform strings into instances of :class:`Symbol` class.

x,y,z = sym.symbols('x,y,z') #Arbitary Vector

f = sym.Eq(λ_1 + 2*λ_2 + λ_3 , x)
g = sym.Eq(λ_1 + 4*λ_2 + 4*λ_3 , y)
h = sym.Eq(-2*λ_1 - λ_2 + 2*λ_3 , z)

a_B = sym.solve([f,g,h],(λ_1,λ_2,λ_3))    #Algebraically solves equations and systems of equations.

print("Coordinates of 'a' in basis B : ", a_B)


Coordinates of 'a' in basis B :  {λ_1: -12*x + 5*y - 4*z, λ_2: 10*x - 4*y + 3*z, λ_3: -7*x + 3*y - 2*z}


In [28]:
#Excercise 2
#****************************************************************************
from scipy.linalg import qr
from sympy import Matrix

In [29]:
def qr_ker(A, tol=None):
    Q, R, P = qr(A.T, mode='full', pivoting=True)
    tol = np.finfo(R.dtype).eps if tol is None else tol
    rnk = min(A.shape) - np.abs(np.diag(R))[::-1].searchsorted(tol)
    return Q[:, rnk:].conj()

A = np.matrix([[1,-2,1], [2,5,-3], [4,1,-1]])
ker_A = qr_ker(A)

In [30]:
#Ques-1
print(" Basis of Ker(A) :",ker_A)

 Basis of Ker(A) : [[0.09667365]
 [0.48336824]
 [0.87006284]]


In [31]:
dim_E = la.matrix_rank(A)
print("dim(E)) is :",dim_E)
dim_ker_A = la.matrix_rank(ker_A)
print("dim(ker(A) is :",dim_ker_A)

dim(E)) is : 2
dim(ker(A) is : 1


In [32]:
#Ques-2
dim_Im_A = dim_E - dim_ker_A
print("dim(Im(A) is :",dim_Im_A)

dim(Im(A) is : 1


In [33]:
#Ques-3 
#Find Basis of Ker(A) and Im(A)
A = Matrix(A)
print("Basis of Ker(A)  are : ",A.nullspace()) #default way
print("Basis of Im(A) are : ",A.columnspace())

Basis of Ker(A)  are :  [Matrix([
[1/9],
[5/9],
[  1]])]
Basis of Im(A) are :  [Matrix([
[1],
[2],
[4]]), Matrix([
[-2],
[ 5],
[ 1]])]


In [34]:
#Ques-4 -- Is A Bijective???
def isbijectiv(n,t):
    l=len;
    d,c=zip(*set(t));
    x=l(set(c));
    return(x+l(set(d))==l(c)*2)+(x==n)*2

isb = True
isb = (isbijectiv(2, [(1,-2,1),(2.5,-3),(4,1,-1)])==3)

if isb == True:# => to check bijective or not
    print("A is Bjective")
else:
    print("A is Not Bijective")

A is Not Bijective


In [35]:
#Excercise 3
#****************************************************************************

import pandas as pd

f = pd.read_excel('C:/Users/Krishna/Downloads/LinearAlgebra_Data.xlsx',headers=0) #from file Location, it reads the file
M = np.array(f)
a = M[:,1]
s = M[:,2]
d = M[:,3]

f.head(3)

Driver ID  A (g/l)  S (km/h)  D (m)
0          1     0.10       101     79
1          2     0.07        90     65
2          3     0.61        94     97

In [36]:
D = np.dot(M.T,M)
D

array([[4.29250e+04, 3.71310e+02, 1.13636e+05, 9.03920e+04],
       [3.71310e+02, 5.93610e+00, 1.29540e+03, 1.12351e+03],
       [1.13636e+05, 1.29540e+03, 4.03000e+05, 3.26853e+05],
       [9.03920e+04, 1.12351e+03, 3.26853e+05, 2.72180e+05]])

In [37]:
#Ques-2.b
#Calculating lambdas - Determining Orthogonal projections of d onto F
λo = np.dot(d,np.ones(50))/np.dot(np.ones(50),np.ones(50))#np.ones -     Return a new array of given shape and type, filled with ones.
λ1 = np.dot(d,a)/np.dot(a,a)
λ2 = np.dot(d,s)/np.dot(s,s)
print("λo Value :",λo)
print("λ1 Value :",λ1)
print("λ2 Value :",λ2)

λo Value : 72.08
λ1 Value : 189.26736409427065
λ2 Value : 0.8110496277915633


In [44]:
#Ques-2.c

#Calculating Mean Square Error(MSE)
mse = 0
for i in range(0,50):
    mse = (d[i] - λo - λ1*a[i] - λ2*s[i])**2
mse = mse/50

print("Mean Squared Error : ",mse)

Mean Squared Error :  145.52171822291734
